import MonoidProduct.Semilattice.Final
set_option linter.style.header false
set_option linter.unusedSectionVars false

/-!
# An infinite ambient semilattice

`MonoidProduct/Semilattice/Final.lean` asks the value type to be finite, because the
scan's branch labels and outputs must be.  That is not a real restriction.  Only
the finitely many values the letters can produce, and the joins of those, ever
occur; and with a finite letter type there are finitely many of them however
large the ambient semilattice is.

So let `M` be any `SemilatticeSup`, `m : σ → M` with `σ` finite, and

  `L_m = supClosure (range m)`,

mathlib's closure under **nonempty** finite joins — exactly the object wanted,
since no bottom is silently inserted and `WithBot L_m` really has `|L_m| + 1`
elements.  `Set.Finite.supClosure` makes it finite, `Subtype.semilatticeSup`
makes the subtype a semilattice, and the letters land in it by
`subset_supClosure`.  Running the finite theorem there gives

  `ADV±(x ↦ ⋁ᵢ m (xᵢ)) ≤ 16 √(n ⌊log₂(|L_m|+1)⌋)`,

with the logarithm of the **generated** subsemilattice, not of anything ambient.

The transport back to `M` is free: the inclusion `L_m ↪ M` is injective and
preserves nonempty finite joins, so the subtype-valued product and the
ambient-valued one induce the same partition of inputs, and a dual solution sees
nothing else.
-/

namespace MonoidProduct
open QuantumQueryComplexity

variable {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
variable {M : Type*} [SemilatticeSup M] [DecidableEq M]
variable {σ : Type*} [Fintype σ] [DecidableEq σ] [Nonempty σ]

/-! ## The generated subsemilattice -/

/-- The finite subsemilattice generated by the letters' values: closure of the
range of `m` under nonempty finite joins. -/
def Generated (m : σ → M) : Type _ := {a : M // a ∈ supClosure (Set.range m)}

namespace Generated

variable {m : σ → M}

instance : CoeOut (Generated m) M := ⟨Subtype.val⟩

lemma supClosed : SupClosed (supClosure (Set.range m)) := supClosed_supClosure

instance instSemilatticeSup : SemilatticeSup (Generated m) :=
  Subtype.semilatticeSup fun _ _ hx hy => supClosed hx hy

noncomputable instance instFintype : Fintype (Generated m) :=
  ((Set.finite_range m).supClosure).fintype

noncomputable instance instDecidableEq : DecidableEq (Generated m) :=
  Classical.decEq _

/-- A letter, viewed in the generated subsemilattice. -/
def of (m : σ → M) (s : σ) : Generated m :=
  ⟨m s, subset_supClosure (Set.mem_range_self s)⟩

@[simp] lemma coe_of (s : σ) : ((of m s : Generated m) : M) = m s := rfl

instance instNonempty : Nonempty (Generated m) := ⟨of m (Classical.arbitrary σ)⟩

@[simp] lemma coe_sup (a b : Generated m) : ((a ⊔ b : Generated m) : M) = a ⊔ b :=
  Subtype.coe_sup (fun _ _ hx hy => supClosed hx hy) a b

lemma coe_le_coe {a b : Generated m} : ((a : M) ≤ b) ↔ a ≤ b := Subtype.coe_le_coe

lemma coe_injective : Function.Injective (Subtype.val : Generated m → M) :=
  Subtype.coe_injective

end Generated

/-! ## The product descends to the generated subsemilattice -/

/-- Every value the product can take lies in the generated subsemilattice. -/
lemma joinMap_mem_supClosure (m : σ → M) (x : ι → σ) :
    joinMap (ι := ι) m x ∈ supClosure (Set.range m) :=
  supClosed_supClosure.finsetSup'_mem Finset.univ_nonempty
    fun i _ => subset_supClosure (Set.mem_range_self (x i))

/-- **The product computed in the subsemilattice is the product computed in
`M`.**  Both inequalities are `joinMap_le` against the other side. -/
lemma coe_joinMap_of (m : σ → M) (x : ι → σ) :
    ((joinMap (ι := ι) (Generated.of m) x : Generated m) : M)
      = joinMap (ι := ι) m x := by
  refine le_antisymm ?_ ?_
  · have h : joinMap (ι := ι) (Generated.of m) x
        ≤ (⟨joinMap (ι := ι) m x, joinMap_mem_supClosure m x⟩ : Generated m) := by
      refine joinMap_le fun i => ?_
      exact Generated.coe_le_coe.1 (le_joinMap m x i)
    exact h
  · refine joinMap_le fun i => ?_
    rw [← Generated.coe_of (m := m) (x i)]
    exact Generated.coe_le_coe.2 (le_joinMap (Generated.of m) x i)

/-! ## The bound -/

/-- **`ADV±(⋁ᵢ m (xᵢ)) ≤ 16 √(n ⌊log₂(|L_m|+1)⌋)` for any ambient semilattice.**

`L_m` is the subsemilattice the letters generate, which is finite because the
letter type is; the ambient `M` may be infinite and is never counted.  This is
the fixed-generator formulation: the bound holds for every input in `ι → σ`, with
`L_m` the closure of *all* allowed letter values. -/
theorem advPM_joinMap_ambient_le (m : σ → M) :
    advPM (joinMap m : (ι → σ) → M)
      ≤ 16 * Real.sqrt ((Fintype.card ι : ℝ)
          * (joinBits (Generated m) : ℝ)) := by
  obtain ⟨P, hP⟩ := exists_joinMap_dual_isCostLe (ι := ι) (A := Generated m)
    (σ := σ) (Generated.of m)
  -- the dual sees only which inputs share a value, and the inclusion is injective
  have hcon : ∀ x y : ι → σ,
      (∑ i, if x i = y i then (0 : ℝ) else ∑ k, P.u x i k * P.v y i k)
        = if joinMap (ι := ι) m x = joinMap (ι := ι) m y then 0 else 1 := by
    intro x y
    rw [P.constraint x y]
    by_cases hxy : joinMap (ι := ι) (Generated.of m) x
        = joinMap (ι := ι) (Generated.of m) y
    · rw [if_pos hxy, if_pos (show joinMap (ι := ι) m x = joinMap (ι := ι) m y from by
        rw [← coe_joinMap_of m x, ← coe_joinMap_of m y, hxy])]
    · rw [if_neg hxy, if_neg (show ¬ joinMap (ι := ι) m x = joinMap (ι := ι) m y from
        fun hc => hxy (Generated.coe_injective (by
          rw [coe_joinMap_of m x, coe_joinMap_of m y, hc])))]
  exact advPM_le_of_dualPair ⟨P.u, P.v, hcon⟩ (by positivity) ⟨hP.1, hP.2⟩

end MonoidProduct
