/-
Copyright (c) 2026 Troy Lee. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Troy Lee
-/
import MonoidProduct.Aperiodic.CommJTrivial
import MonoidProduct.Aperiodic.CubeRoot
import MonoidProduct.Aperiodic.CubeRoot.ActionCompiler
import MonoidProduct.Aperiodic.CubeRoot.ActionCost
import MonoidProduct.Aperiodic.CubeRoot.ActionTarget
import MonoidProduct.Aperiodic.CubeRoot.AdaptiveCall
import MonoidProduct.Aperiodic.CubeRoot.ApexAdapter
import MonoidProduct.Aperiodic.CubeRoot.ApexBuild
import MonoidProduct.Aperiodic.CubeRoot.ApexData
import MonoidProduct.Aperiodic.CubeRoot.ApexJoint
import MonoidProduct.Aperiodic.CubeRoot.Assembly
import MonoidProduct.Aperiodic.CubeRoot.AxisPacket
import MonoidProduct.Aperiodic.CubeRoot.AxisRecurrence
import MonoidProduct.Aperiodic.CubeRoot.Basic
import MonoidProduct.Aperiodic.CubeRoot.Compression
import MonoidProduct.Aperiodic.CubeRoot.Exports
import MonoidProduct.Aperiodic.CubeRoot.FiniteAction
import MonoidProduct.Aperiodic.CubeRoot.FirstEntry
import MonoidProduct.Aperiodic.CubeRoot.FixedApex
import MonoidProduct.Aperiodic.CubeRoot.Green
import MonoidProduct.Aperiodic.CubeRoot.GreenCalibration
import MonoidProduct.Aperiodic.CubeRoot.KernelFiltration
import MonoidProduct.Aperiodic.CubeRoot.LocallyThin
import MonoidProduct.Aperiodic.CubeRoot.LocallyThinCalibration
import MonoidProduct.Aperiodic.CubeRoot.LocallyThinCompiler
import MonoidProduct.Aperiodic.CubeRoot.Main
import MonoidProduct.Aperiodic.CubeRoot.MatrixRank
import MonoidProduct.Aperiodic.CubeRoot.MatrixWord
import MonoidProduct.Aperiodic.CubeRoot.MunnLayer
import MonoidProduct.Aperiodic.CubeRoot.MunnPackage
import MonoidProduct.Aperiodic.CubeRoot.PrincipalAction
import MonoidProduct.Aperiodic.CubeRoot.PrincipalFactor
import MonoidProduct.Aperiodic.CubeRoot.PrincipalMatrix
import MonoidProduct.Aperiodic.CubeRoot.RadicalStep
import MonoidProduct.Aperiodic.CubeRoot.RadicalTower
import MonoidProduct.Aperiodic.CubeRoot.Recurrence
import MonoidProduct.Aperiodic.CubeRoot.Rees
import MonoidProduct.Aperiodic.CubeRoot.ReesBlock
import MonoidProduct.Aperiodic.CubeRoot.SolvedRecurrence
import MonoidProduct.Aperiodic.CubeRoot.StrictParent
import MonoidProduct.Aperiodic.CubeRoot.TargetAction
import MonoidProduct.Aperiodic.DA
import MonoidProduct.Aperiodic.Decomposition
import MonoidProduct.Aperiodic.Defs
import MonoidProduct.Aperiodic.Division
import MonoidProduct.Aperiodic.EqProd
import MonoidProduct.Aperiodic.Examples
import MonoidProduct.Aperiodic.Grid
import MonoidProduct.Aperiodic.Ideals
import MonoidProduct.Aperiodic.Induction
import MonoidProduct.Aperiodic.Infix
import MonoidProduct.Aperiodic.InfixCost
import MonoidProduct.Aperiodic.Prefix
import MonoidProduct.Aperiodic.RTrivial
import MonoidProduct.Aperiodic.Semigroup
import MonoidProduct.Aperiodic.Split
import MonoidProduct.Aperiodic.Suffix
import MonoidProduct.Capped.Breadth
import MonoidProduct.Capped.Defs
import MonoidProduct.Capped.Embed
import MonoidProduct.Capped.LengthBreadth
import MonoidProduct.Capped.Lower
import MonoidProduct.Capped.RTrivial
import MonoidProduct.Capped.Theta
import MonoidProduct.Capped.Width
import MonoidProduct.Dyck.Amplify
import MonoidProduct.Dyck.AndStar
import MonoidProduct.Dyck.Blocks
import MonoidProduct.Dyck.Breadth
import MonoidProduct.Dyck.Concat
import MonoidProduct.Dyck.Defs
import MonoidProduct.Dyck.ExactCount
import MonoidProduct.Dyck.Final
import MonoidProduct.Dyck.IterExact
import MonoidProduct.Dyck.Lower
import MonoidProduct.Dyck.Monoid.Algebra
import MonoidProduct.Dyck.Monoid.Defs
import MonoidProduct.Dyck.Monoid.Green
import MonoidProduct.Dyck.Monoid.NormalForm
import MonoidProduct.Dyck.Monoid.Peel
import MonoidProduct.Dyck.Monoid.Reduce
import MonoidProduct.Dyck.Monoid.Sandwich
import MonoidProduct.Infix.Code
import MonoidProduct.Infix.Defs
import MonoidProduct.Infix.Dual
import MonoidProduct.Infix.Monoids
import MonoidProduct.Infix.Negative
import MonoidProduct.Infix.Order
import MonoidProduct.Infix.Rees
import MonoidProduct.Infix.Saturation
import MonoidProduct.Infix.Typed
import MonoidProduct.Infix.TypedDual
import MonoidProduct.Infix.Uniform
import MonoidProduct.Layer.Lower
import MonoidProduct.Matroid
import MonoidProduct.Matroid.Graphic
import MonoidProduct.Matroid.GraphicRank
import MonoidProduct.Matroid.Greedy
import MonoidProduct.Matroid.GreedyMonoid
import MonoidProduct.Matroid.GreedyWeight
import MonoidProduct.Matroid.Quantum
import MonoidProduct.Matroid.Records
import MonoidProduct.Matroid.Selection
import MonoidProduct.Matroid.Vector
import MonoidProduct.Matroid.Width
import MonoidProduct.Ordered.Correct
import MonoidProduct.Ordered.Cost
import MonoidProduct.Ordered.FiniteProb
import MonoidProduct.Ordered.LogRank
import MonoidProduct.Ordered.LogRankCorrect
import MonoidProduct.Ordered.LogRankCost
import MonoidProduct.Ordered.LogRankRoot
import MonoidProduct.Ordered.MedianFrontier
import MonoidProduct.Ordered.Merge
import MonoidProduct.Ordered.MergeSeeded
import MonoidProduct.Ordered.PiProb
import MonoidProduct.Ordered.RankDoubling
import MonoidProduct.Ordered.Records
import MonoidProduct.Ordered.Root
import MonoidProduct.Ordered.Summary
import MonoidProduct.Ordered.Thinning
import MonoidProduct.Ordered.TreeSampling
import MonoidProduct.Ordered.Verify
import MonoidProduct.Promise.Semilattice
import MonoidProduct.Quantum.AGSApplications
import MonoidProduct.Quantum.AcceptanceCommutative
import MonoidProduct.Quantum.AcceptanceE
import MonoidProduct.Quantum.AcceptanceF
import MonoidProduct.Quantum.AcceptanceG
import MonoidProduct.Quantum.AcceptanceK
import MonoidProduct.Quantum.AcceptanceP
import MonoidProduct.Quantum.AcceptanceR
import MonoidProduct.Quantum.AcceptanceS
import MonoidProduct.Quantum.AcceptanceU
import MonoidProduct.Quantum.AcceptanceV
import MonoidProduct.Quantum.Applications
import MonoidProduct.Quantum.BrandtTwoColour
import MonoidProduct.Quantum.CommutativeLower
import MonoidProduct.Quantum.CubeRootApplications
import MonoidProduct.Quantum.Division
import MonoidProduct.Quantum.DivisionApplications
import MonoidProduct.Quantum.DivisionInfinite
import MonoidProduct.Quantum.DivisionSemigroup
import MonoidProduct.Quantum.DyckApplications
import MonoidProduct.Quantum.DyckLanguageLower
import MonoidProduct.Quantum.DyckNearLinear
import MonoidProduct.Quantum.Envelope
import MonoidProduct.Quantum.EnvelopeDisplays
import MonoidProduct.Quantum.FollowupAcceptance
import MonoidProduct.Quantum.OneHotApplications
import MonoidProduct.Quantum.OrderedAcceptance
import MonoidProduct.Quantum.OrderedApplications
import MonoidProduct.Quantum.OrderedLogAcceptance
import MonoidProduct.Quantum.OrderedLogApplications
import MonoidProduct.Quantum.OrderedTruthful
import MonoidProduct.Quantum.OrderedVerified
import MonoidProduct.Quantum.PaperForms
import MonoidProduct.Quantum.RTrivialApplications
import MonoidProduct.Quantum.RTrivialPaper
import MonoidProduct.Quantum.SemilatticeApplications
import MonoidProduct.Quantum.StrictStockApplications
import MonoidProduct.Quantum.WidthApplications
import MonoidProduct.Semilattice.Critical
import MonoidProduct.Semilattice.Final
import MonoidProduct.Semilattice.Generated
import MonoidProduct.Semilattice.Record
import MonoidProduct.Semilattice.Semigroup
import MonoidProduct.SemilatticeCerts
import MonoidProduct.Simon.Blue
import MonoidProduct.Simon.Chain
import MonoidProduct.Simon.Defs
import MonoidProduct.Simon.Kernel
import MonoidProduct.Simon.Main
import MonoidProduct.Simon.Red
import MonoidProduct.Simon.Words
import MonoidProduct.Stock.Aperiodic
import MonoidProduct.Stock.GeneralPrices
import MonoidProduct.Stock.Strict
import MonoidProduct.Trichotomy.Index
import MonoidProduct.Trichotomy.Main
import MonoidProduct.Trichotomy.PaperForms
import MonoidProduct.Trichotomy.Semigroup
import MonoidProduct.Tropical.Breadth
import MonoidProduct.Tropical.Defs
import MonoidProduct.Tropical.LinProd
import MonoidProduct.Tropical.Lower
import MonoidProduct.Tropical.Mask
import MonoidProduct.Tropical.Path
import MonoidProduct.Tropical.Support
import MonoidProduct.Tropical.Unitriangular
import MonoidProduct.UT.Breadth
import MonoidProduct.UT.Defs
import MonoidProduct.UT.Lower
import MonoidProduct.UT.Main
import MonoidProduct.UT.Upper
import MonoidProduct.Width.Breadth
import MonoidProduct.Width.BreadthBounds
import MonoidProduct.Width.Deletion
import MonoidProduct.Width.ErdosRadoComparison
import MonoidProduct.Width.EssentialWord
import MonoidProduct.Width.Incidence
import MonoidProduct.Width.IndexK
import MonoidProduct.Width.IndexTwo
import MonoidProduct.Width.Instances
import MonoidProduct.Width.Main
import MonoidProduct.Width.Numeric
import MonoidProduct.Width.PaperForms
import MonoidProduct.Width.Product
import MonoidProduct.Width.ProductSunflower
import MonoidProduct.Width.PromiseWidth
import MonoidProduct.Width.RaoBCW
import MonoidProduct.Width.SmallClauses
import MonoidProduct.Width.StableOrder
import MonoidProduct.Width.Summary
import MonoidProduct.WidthCerts
import QuantumQueryComplexity.Quantum.TreeSearch

/-!
# Quantum query complexity of semigroup and monoid products

Root module of the formalization of Troy Lee and Miklos Santha,
*The quantum query complexity of the semigroup product problem*.
See `docs/monoid-product/PAPER_CORRESPONDENCE.md` for the map from the paper's
statements to Lean declarations.
-/
