import MonoidProduct.Aperiodic.Ideals
import MonoidProduct.Quantum.Applications
import MonoidProduct.Quantum.CubeRootApplications
import QuantumQueryComplexity.Quantum.OneHotSimulation
set_option linter.style.header false
set_option linter.unusedSectionVars false
set_option linter.unusedDecidableInType false
set_option linter.unusedFintypeInType false

/-!
# The rank function and the fixed-monoid trichotomy, in the paper's form

`monoid.tex` Propositions `prop:rank-mono` and `prop:identity`, and Theorem
`thm:fixed-monoid-trichotomy`, stated as the paper states them.

* **The rank** `ρ(m) = |M| − |MmM|` (`idealRank`), the number of elements
  outside the principal two-sided ideal `twoIdeal m`.  It grows along products
  (`idealRank_le_idealRank_mul_left/right`, `prop:rank-mono`), and in a finite
  aperiodic monoid it vanishes exactly at the identity
  (`idealRank_eq_zero_iff`, the second clause of `prop:identity`).  The AGS
  recursion itself descends on the ideal-chain depth `jLevel`
  (`Aperiodic/Ideals.lean`); the rank is recorded here for the paper's
  statements.
* **The trivial regime at the query level**: for `|M| = 1` the product is
  constant, so it costs zero queries in both oracle models
  (`qQuery_prodFun_of_subsingleton`, `oneHotQQuery_prodFun_of_subsingleton`).
* **The whole trichotomy at the query level**: the semigroup clause
  (`fixed_semigroup_trichotomy_qQuery`, including the Boolean postprocessing)
  and the three monoid regimes (`fixed_monoid_trichotomy_qQuery`), assembled
  from the regime theorems of `Quantum/Applications.lean` and
  `Quantum/CubeRootApplications.lean`.
-/

namespace MonoidProduct
open QuantumQueryComplexity

/-! ## The rank -/

section Rank

variable {M : Type*} [Monoid M] [Fintype M] [DecidableEq M]

/-- **The rank** `ρ(m) = |M| − |MmM|`: the number of elements outside the
principal two-sided ideal generated by `m`. -/
def idealRank (m : M) : ℕ := Fintype.card M - (twoIdeal m).card

lemma idealRank_add_card_twoIdeal (m : M) :
    idealRank m + (twoIdeal m).card = Fintype.card M := by
  have h : (twoIdeal m).card ≤ Fintype.card M := Finset.card_le_univ _
  unfold idealRank
  omega

/-- The identity has rank `0`: `M1M = M`. -/
@[simp] lemma idealRank_one : idealRank (1 : M) = 0 := by
  simp [idealRank, twoIdeal_one]

/-- **`prop:rank-mono`, left factor**: `ρ(p) ≤ ρ(pq)`, since `MpqM ⊆ MpM`. -/
theorem idealRank_le_idealRank_mul_left (p q : M) :
    idealRank p ≤ idealRank (p * q) :=
  Nat.sub_le_sub_left (Finset.card_le_card (twoIdeal_mul_subset_left p q)) _

/-- **`prop:rank-mono`, right factor**: `ρ(q) ≤ ρ(pq)`, since `MpqM ⊆ MqM`. -/
theorem idealRank_le_idealRank_mul_right (p q : M) :
    idealRank q ≤ idealRank (p * q) :=
  Nat.sub_le_sub_left (Finset.card_le_card (twoIdeal_mul_subset_right p q)) _

/-- **`prop:rank-mono`** (`monoid.tex`): for any `p, q ∈ M`,
`ρ(p) ≤ ρ(pq)` and `ρ(q) ≤ ρ(pq)`. -/
theorem idealRank_mono (p q : M) :
    idealRank p ≤ idealRank (p * q) ∧ idealRank q ≤ idealRank (p * q) :=
  ⟨idealRank_le_idealRank_mul_left p q, idealRank_le_idealRank_mul_right p q⟩

/-- Rank `0` means the two-sided ideal is everything. -/
lemma twoIdeal_eq_univ_of_idealRank_eq_zero {m : M} (h : idealRank m = 0) :
    twoIdeal m = Finset.univ := by
  have h1 := idealRank_add_card_twoIdeal m
  rw [h, zero_add] at h1
  exact Finset.eq_univ_of_card _ h1

end Rank

/-! ## `prop:identity` -/

section Identity

variable {M : Type*} [Monoid M] [Fintype M] [DecidableEq M] [IsAperiodicMonoid M]

/-- **`prop:identity`, second clause**: in a finite aperiodic monoid,
`ρ(m) = 0` iff `m = 1`.  If `MmM = M ∋ 1`, then `1 = amb`, and the first
clause forces `m = 1`. -/
theorem idealRank_eq_zero_iff {m : M} : idealRank m = 0 ↔ m = 1 := by
  refine ⟨fun h => ?_, fun h => by rw [h, idealRank_one]⟩
  have hone : (1 : M) ∈ twoIdeal m := by
    rw [twoIdeal_eq_univ_of_idealRank_eq_zero h]
    exact Finset.mem_univ _
  obtain ⟨a, b, hab⟩ := mem_twoIdeal.1 hone
  exact (mul_eq_one_iff'.1 (mul_eq_one_iff'.1 hab).1).2

/-- **`prop:identity`** (`monoid.tex`), both clauses: in a finite aperiodic
monoid, `p₁ p₂ ⋯ pₙ = 1` implies `p₁ = ⋯ = pₙ = 1`; consequently
`ρ(m) = 0` iff `m = 1`.  The first clause holds without finiteness
(`List.prod_eq_one_iff'`). -/
theorem prop_identity :
    (∀ (n : ℕ) (p : Fin n → M), (List.ofFn p).prod = 1 → ∀ i, p i = 1)
      ∧ ∀ m : M, idealRank m = 0 ↔ m = 1 := by
  refine ⟨fun n p h i => ?_, fun m => idealRank_eq_zero_iff⟩
  exact (List.prod_eq_one_iff' _).1 h (p i) (List.mem_ofFn.2 ⟨i, rfl⟩)

end Identity

/-! ## The trivial regime at the query level -/

section Trivial

variable {M : Type} [Monoid M] [Fintype M] [DecidableEq M] {n : ℕ}

/-- **A trivial monoid costs zero queries** (`thm:fixed-monoid-trichotomy`,
the case `|M| = 1`): the product is constant, so the zero-query algorithm
announcing `1` computes it, at every error `ε ≥ 0`. -/
theorem qQuery_prodFun_of_subsingleton [Subsingleton M] {ε : ℝ} (hε : 0 ≤ ε) :
    qQuery (fun w : Fin n → M => wordProd (id : M → M) w) ε = 0 :=
  qQueryOn_const_eq_zero id (c := 1) (fun _ => Subsingleton.elim _ _) hε

/-- The same in the one-hot oracle model: one-hot complexity is at most twice
the native one. -/
theorem oneHotQQuery_prodFun_of_subsingleton [Subsingleton M] {ε : ℝ}
    (hε : 0 ≤ ε) :
    oneHotQQuery (fun w : Fin n → M => wordProd (id : M → M) w) ε = 0 := by
  have h := oneHotQQueryOn_le_two_mul_qQueryOn
    (read := (id : (Fin n → M) → Fin n → M))
    (f := fun w : Fin n → M => wordProd (id : M → M) w)
    (fun x y hxy => by rw [show x = y from hxy]) hε
  have h0 : qQuery (fun w : Fin n → M => wordProd (id : M → M) w) ε = 0 :=
    qQuery_prodFun_of_subsingleton hε
  unfold oneHotQQuery
  unfold qQuery at h0
  omega

end Trivial

/-! ## The trichotomy at the query level -/

section Trichotomy

/-- **`thm:fixed-monoid-trichotomy`, the semigroup clause, at the query
level**: a finite nonaperiodic semigroup `S` has
`(1/36)·(n+1)/2 ≤ Q_{1/3}(Prod_{S,n+1}) ≤ n + 1`, i.e. `Θ_S(n)`; and the
lower bound already holds for a Boolean postprocessing `post : S → Bool` of
the product, on a promise of two-letter words (letters `s, s²`, Hamming
weight `⌊(n+1)/2⌋` or one more).

Words are indexed by `Fin (n + 1)` because a semigroup has no empty
product. -/
theorem fixed_semigroup_trichotomy_qQuery {S : Type} [Semigroup S] [Fintype S]
    [DecidableEq S] (h : ¬ IsAperiodicSemigroup S) (n : ℕ) :
    ((1 / 36 : ℝ) * (((n + 1 : ℕ) : ℝ) / 2)
        ≤ (qQuery (fun w : Fin (n + 1) → S => semigroupProd n w) (1 / 3) : ℝ)
      ∧ qQuery (fun w : Fin (n + 1) → S => semigroupProd n w) (1 / 3) ≤ n + 1)
    ∧ ∃ (s : S) (post : S → Bool),
        (1 / 36 : ℝ) * (((n + 1 : ℕ) : ℝ) / 2)
          ≤ (qQueryOn (layerRead (n := n + 1) (r := (n + 1) / 2) (sLetter s))
              (fun x => post (semigroupProd n
                (layerRead (n := n + 1) (r := (n + 1) / 2) (sLetter s) x)))
              (1 / 3) : ℝ) := by
  classical
  obtain ⟨s, hs⟩ := exists_nonaperiodic_semigroup_elem h
  have : Nonempty S := ⟨s⟩
  refine ⟨⟨qQuery_semigroupProd_lower_of_not_aperiodic h n,
    nonaperiodic_semigroup_qQuery_upper (by norm_num) n⟩, ?_⟩
  refine ⟨s, fun t : S => decide ((t : WithOne S)
      = (s : WithOne S) ^ ((n + 1) + (n + 1) / 2 + 1)), ?_⟩
  have hfun := decide_coe_semigroupProd_eq_layerOut hs n
  have hpar := mul_advPMOn_le_qQueryOn_of_error_third
    (read := layerRead (n := n + 1) (r := (n + 1) / 2) (sLetter s))
    (f := layerOut (n := n + 1) (r := (n + 1) / 2))
    (separates_of_injective (layerRead_injective (sLetter_injective hs)) _)
  rw [← hfun] at hpar
  refine le_trans ?_ hpar
  refine mul_le_mul_of_nonneg_left ?_ (by norm_num)
  rw [hfun]
  exact half_le_advPMOn_layerOut (sLetter_injective hs) (by omega)

variable {M : Type} [Monoid M] [Fintype M] [DecidableEq M] {n : ℕ}

/-- The product of zero letters is constant, so it costs nothing. -/
private lemma qQuery_prodFun_zero :
    qQuery (fun w : Fin 0 → M => wordProd (id : M → M) w) (1 / 3) = 0 :=
  qQueryOn_const_eq_zero id (c := wordProd (id : M → M) (fun i : Fin 0 => i.elim0))
    (fun w => congrArg _ (Subsingleton.elim _ _)) (by norm_num)

/-- Reading every letter: `Q_{1/3}(Prod_{M,n}) ≤ n` for every finite monoid. -/
private lemma qQuery_prodFun_le_length :
    qQuery (fun w : Fin n → M => wordProd (id : M → M) w) (1 / 3) ≤ n := by
  have : Nonempty M := ⟨1⟩
  have h := qQueryOn_le_card
    (read := (id : (Fin n → M) → Fin n → M))
    (f := fun w : Fin n → M => wordProd (id : M → M) w)
    (fun x y hxy => by rw [show x = y from hxy]) (by norm_num : (0 : ℝ) ≤ 1 / 3)
  rwa [Fintype.card_fin] at h

/-- **`thm:fixed-monoid-trichotomy`, the monoid trichotomy, at the query
level**: for every finite monoid `M` and every word length `n`,
writing `Q = Q_{1/3}(Prod_{M,n})` and `N = |M|`,

* `|M| = 1`: `Q = 0`;
* `M` nontrivial and aperiodic: `(1/36)·√n ≤ Q` and
  `Q ≤ min{n, √n · log(n+2)^(2^20 · (N·log(N+2))^(1/3))}`, i.e. `Θ̃_M(√n)`
  in the paper's sense (an `Ω(√n)` lower bound and an
  `O_M(√n (log(n+2))^{O_M(1)})` upper bound);
* `M` nonaperiodic: `(1/36)·(n/2) ≤ Q ≤ n`, i.e. `Θ_M(n)`.

The three cases are exhaustive: a nonaperiodic monoid is nontrivial. -/
theorem fixed_monoid_trichotomy_qQuery :
    (Subsingleton M →
        qQuery (fun w : Fin n → M => wordProd (id : M → M) w) (1 / 3) = 0)
      ∧ (¬ Subsingleton M → IsAperiodicMonoid M →
        (1 / 36 : ℝ) * Real.sqrt n
            ≤ (qQuery (fun w : Fin n → M => wordProd (id : M → M) w) (1 / 3) : ℝ)
          ∧ (qQuery (fun w : Fin n → M => wordProd (id : M → M) w) (1 / 3) : ℝ)
            ≤ min (n : ℝ) (Real.sqrt (n : ℝ)
              * Real.log ((n : ℝ) + 2)
                ^ (1048576 * (((Fintype.card M : ℝ)
                    * Real.log ((Fintype.card M : ℝ) + 2)) ^ ((3 : ℝ)⁻¹)))))
      ∧ (¬ IsAperiodicMonoid M →
        (1 / 36 : ℝ) * ((n : ℝ) / 2)
            ≤ (qQuery (fun w : Fin n → M => wordProd (id : M → M) w) (1 / 3) : ℝ)
          ∧ qQuery (fun w : Fin n → M => wordProd (id : M → M) w) (1 / 3) ≤ n) := by
  refine ⟨fun h => ?_, fun hnt hap => ⟨?_, ?_⟩, fun hna => ⟨?_, qQuery_prodFun_le_length⟩⟩
  · exact qQuery_prodFun_of_subsingleton (by norm_num)
  · rcases Nat.eq_zero_or_pos n with rfl | hn
    · simp
    · exact qQuery_lower_of_not_subsingleton hnt hn
  · rcases Nat.eq_zero_or_pos n with rfl | hn
    · rw [qQuery_prodFun_zero]
      simp
    · exact aperiodic_qQuery_intro hn
  · rcases Nat.lt_or_ge n 2 with hn | hn
    · interval_cases n
      · simp
      · -- a single letter: the nontrivial bound `(1/36)·√1` is already larger
        obtain ⟨g, hg⟩ := exists_nonaperiodic_elem hna
        have hlow := nontrivial_qQuery_lower_total (n := 1)
          (ne_one_of_nonaperiodic hg) le_rfl
        rw [Nat.cast_one, Real.sqrt_one] at hlow
        push_cast
        linarith
    · exact qQuery_lower_of_not_aperiodic hna hn

end Trichotomy

end MonoidProduct
