import MonoidProduct.Aperiodic.CubeRoot.ApexBuild
set_option linter.style.header false
set_option linter.unusedSectionVars false
set_option linter.unusedDecidableInType false
set_option linter.unusedFintypeInType false

/-!
# The joint coordinate map

Everything `ApexPackage` asks for **except** the kernel's nilpotency, which is
proved separately (`KernelFiltration.lean` and its sequels) and is the hard
core of the Munn–Ponizovskiĭ construction.

**Enumerating the regular classes.**  A regular class is one containing an
idempotent, so the classes are enumerated by the *ideals* the idempotents
generate — `idemIdeals`, a `Finset (Finset M)`.  Indexing by the ideals rather
than by the idempotents is what makes `disjoint` true: two idempotents of one
class generate the same ideal and must not be listed twice.  `Finset.equivFin`
then supplies the `Fin count` the package wants.

**The ambient algebra is `MonoidAlgebra ℚ M`**, which is the package's default
and the common algebra the per-`J` statements
already live over.  `embed` is `MonoidAlgebra.of`, faithful by
`single_left_injective`; `toCoord` is the lift of the product of the
coordinates.

**What is not here.**  `nilExponent` and `kernel_pow`.  Nothing above bears on
them: the joint map's *kernel* is a separate question from its construction, and
it is the kernel that `ApexPackage` and the radical tower actually consume, not any surjectivity of this map.
-/

namespace MonoidProduct
open QuantumQueryComplexity

namespace PrincipalFactor

variable {M : Type} [Monoid M] [Fintype M] [DecidableEq M]

/-! ## Enumerating the regular classes -/

variable (M) in
/-- The ideals generated by idempotents: one per regular `J`-class.  Indexed by
the *ideal*, not the idempotent, so that a class is listed once. -/
noncomputable def idemIdeals : Finset (Finset M) :=
  (Finset.univ.filter fun e : M => e * e = e).image fun e => twoIdeal e

lemma mem_idemIdeals {I : Finset M} :
    I ∈ idemIdeals M ↔ ∃ e : M, IsIdempotentElem e ∧ twoIdeal e = I := by
  simp only [idemIdeals, Finset.mem_image, Finset.mem_filter, Finset.mem_univ, true_and]
  exact ⟨fun ⟨e, he, hI⟩ => ⟨e, he, hI⟩, fun ⟨e, he, hI⟩ => ⟨e, he, hI⟩⟩

/-- A chosen idempotent generating a listed ideal. -/
noncomputable def apexOf {I : Finset M} (hI : I ∈ idemIdeals M) : M :=
  (mem_idemIdeals.1 hI).choose

lemma apexOf_idem {I : Finset M} (hI : I ∈ idemIdeals M) :
    IsIdempotentElem (apexOf hI) := (mem_idemIdeals.1 hI).choose_spec.1

lemma apexOf_twoIdeal {I : Finset M} (hI : I ∈ idemIdeals M) :
    twoIdeal (apexOf hI) = I := (mem_idemIdeals.1 hI).choose_spec.2

/-! ## The listed coordinates -/

variable (M) in
/-- The apex listed at index `k`. -/
noncomputable def jointApex (k : Fin (idemIdeals M).card) : M :=
  apexOf ((idemIdeals M).equivFin.symm k).2

variable (M) in
lemma jointApex_idem (k : Fin (idemIdeals M).card) :
    IsIdempotentElem (jointApex M k) := apexOf_idem _

variable (M) in
lemma jointApex_twoIdeal (k : Fin (idemIdeals M).card) :
    twoIdeal (jointApex M k) = ((idemIdeals M).equivFin.symm k : Finset M) := apexOf_twoIdeal _

variable (M) in
/-- **The rank factorization listed at index `k`**, kept rather than discarded.

Choosing the coordinate from the bare existential `∃ c, c.apex = e` would erase
both the factorization and the fact that `c.rep` is the *compressed Munn*
representation — and neither is recoverable from `ApexCoordinate`, which
remembers only a degree and a monoid hom.  Item 7's layer argument needs both,
so they are chosen here and exported by the `rfl`-lemmas below. -/
noncomputable def jointFactor (k : Fin (idemIdeals M).card) :
    RankFactorization (sandwichMat M (jointApex M k)) :=
  (exists_rankFactorization (sandwichMat M (jointApex M k))).choose

variable (M) in
lemma jointFactor_rank (k : Fin (idemIdeals M).card) :
    (jointFactor M k).d = (sandwichMat M (jointApex M k)).rank :=
  (exists_rankFactorization (sandwichMat M (jointApex M k))).choose_spec

variable (M) in
/-- The coordinate listed at index `k`, built from the retained factorization. -/
noncomputable def jointCoord [IsAperiodicMonoid M] (k : Fin (idemIdeals M).card) :
    ApexCoordinate M :=
  apexCoordinateOf (jointApex_idem M k) (jointFactor M k) (jointFactor_rank M k)

@[simp] lemma jointCoord_apex [IsAperiodicMonoid M] (k : Fin (idemIdeals M).card) :
    (jointCoord M k).apex = jointApex M k := rfl

/-- **The degree is the retained factorization's**, not an opaque number. -/
@[simp] lemma jointCoord_degree [IsAperiodicMonoid M] (k : Fin (idemIdeals M).card) :
    (jointCoord M k).degree = (jointFactor M k).d := rfl

/-- **The representation is the compressed Munn map**, which is the fact the kernel's
nilpotency argument cannot reconstruct from the interface. -/
lemma jointCoord_rep [IsAperiodicMonoid M] (k : Fin (idemIdeals M).card) :
    (jointCoord M k).rep
      = compressedRep (jointFactor M k) (rowColAction M (jointApex M k)) := rfl

/-- **Distinct indices, distinct classes** — which is why the enumeration is by
ideals and not by idempotents. -/
theorem jointCoord_disjoint [IsAperiodicMonoid M] (k k' : Fin (idemIdeals M).card)
    (h : twoIdeal (jointCoord M k).apex = twoIdeal (jointCoord M k').apex) : k = k' := by
  rw [jointCoord_apex, jointCoord_apex, jointApex_twoIdeal, jointApex_twoIdeal] at h
  exact (idemIdeals M).equivFin.symm.injective (Subtype.ext h)

/-- **The enumeration is complete**: every regular class is listed.  The layer
argument needs this direction — `jointCoord_disjoint` only says no class is
listed twice. -/
theorem exists_index_of_isRegularClass [IsAperiodicMonoid M] {a : M}
    (hreg : IsRegularClass a) :
    ∃ k : Fin (idemIdeals M).card, twoIdeal (jointCoord M k).apex = twoIdeal a := by
  obtain ⟨e, hJ, hidem⟩ := isRegularClass_iff_exists_idem.1 hreg
  have hI : twoIdeal e ∈ idemIdeals M := mem_idemIdeals.2 ⟨e, hidem, rfl⟩
  refine ⟨(idemIdeals M).equivFin ⟨twoIdeal e, hI⟩, ?_⟩
  rw [jointCoord_apex, jointApex_twoIdeal, Equiv.symm_apply_apply]
  exact hJ

/-- **The total charge of the listing**, from `sum_degree_sq_le`. -/
theorem charge_jointCoord [IsAperiodicMonoid M] :
    ∑ k, (jointCoord M k).degree ^ 2 ≤ Fintype.card M :=
  sum_degree_sq_le _ jointCoord_disjoint

/-! ## The ambient algebra and the joint map -/

/-- `MonoidAlgebra.of` is faithful — the package's `embed_injective`. -/
theorem of_injective : Function.Injective (MonoidAlgebra.of ℚ M) :=
  fun _ _ h => MonoidAlgebra.single_left_injective (one_ne_zero (α := ℚ)) h

variable (M) in
/-- The product of the coordinates, as a monoid homomorphism. -/
noncomputable def jointRep [IsAperiodicMonoid M] :
    M →* ∀ k : Fin (idemIdeals M).card,
      Matrix (Fin (jointCoord M k).degree) (Fin (jointCoord M k).degree) ℚ :=
  MonoidHom.pi fun k => (jointCoord M k).rep

variable (M) in
/-- **The joint coordinate map** out of the monoid algebra: the package's
`toCoord`. -/
noncomputable def jointAlgHom [IsAperiodicMonoid M] :
    MonoidAlgebra ℚ M →ₐ[ℚ] ∀ k : Fin (idemIdeals M).card,
      Matrix (Fin (jointCoord M k).degree) (Fin (jointCoord M k).degree) ℚ :=
  MonoidAlgebra.lift ℚ _ M (jointRep M)

/-- **The joint map restricts to the coordinates** — the package's
`toCoord_embed`. -/
theorem jointAlgHom_of [IsAperiodicMonoid M] (m : M) (k : Fin (idemIdeals M).card) :
    jointAlgHom M (MonoidAlgebra.of ℚ M m) k = (jointCoord M k).rep m := by
  rw [jointAlgHom, MonoidAlgebra.lift_of]
  rfl

end PrincipalFactor

end MonoidProduct
