import MonoidProduct.Width.Breadth
import MonoidProduct.Width.IndexTwo
import MonoidProduct.Width.IndexK
set_option linter.style.header false
set_option linter.unusedSectionVars false
set_option linter.unusedDecidableInType false
set_option linter.unusedFintypeInType false

/-!
# Breadth bounds from the stabilization identities

The commutative theorems of the paper's Section `sec:lattice`, restated in the
paper's own parameter `β` (`Width/Breadth.lean`) rather than the essential
width they were first formalized in:

| paper | here |
| --- | --- |
| `thm:semilattice-product`, `β ≤ ⌊log₂(L+1)⌋` for `x² = x` | `breadth_le_log_of_idem`, as `β ≤ ⌊log₂ M⌋` (apply it to the submonoid generated by the alphabet to recover `L + 1`) |
| `thm:index-two-width`, `β < 5·log₂ M` for `x³ = x²` | `breadth_lt_five_logb` |
| `thm:index-k-width`, `β = O(k·log M·log log M)` | `breadth_le_bcw`, with the constant of `Width/IndexK.lean` |
| the trivial fallback `β ≤ M − 1` | `breadth_le_card_monoid` (`Width/Breadth.lean`) |

The idempotent bound is proved here directly on the subset product (the
existing semilattice development works with joins in `WithBot A`): the
context products of the subsets of an essential set are pairwise distinct —
a collision `c(S) = c(S')` with `i ∈ S ∖ S'` would give
`c(E) = c(S' ∪ (E ∖ S)) ≤ c(E ∖ {i}) ≤ c(E)`, so deleting `i` would preserve
the product — hence `2^{|E|} ≤ |M|`.  The other two rows are the recorded
width bounds transported through `exists_card_prodEss_eq_breadth` (`β` is
attained by some word) so that the real-valued statements move verbatim.
-/

namespace MonoidProduct
open QuantumQueryComplexity

variable {σ : Type} [Fintype σ] [DecidableEq σ]
variable {M : Type} [Fintype M] [DecidableEq M] [CommMonoid M]

/-! ## Context products, completed -/

section Ctx

variable {ι : Type*} [Fintype ι] [DecidableEq ι] (m : σ → M) (x : ι → σ) (T : Finset ι)

/-- The context product over `S ⊆ V`, completed to `V`. -/
lemma ctxProd_mul_sdiff' {S V : Finset ι} (hSV : S ⊆ V) :
    ctxProd m x T S * ∏ j ∈ V \ S, m (x j) = ctxProd m x T V := by
  rw [ctxProd, ctxProd, mul_assoc, mul_comm (∏ j ∈ S, m (x j)), Finset.prod_sdiff hSV]

lemma ctxProd_prodEss : ctxProd m x T (prodEss m x T) = ∏ j ∈ T, m (x j) := by
  rw [ctxProd, Finset.prod_sdiff (prodEss_subset' m x T)]

end Ctx

/-! ## The idempotent case -/

section Idempotent

variable (hidem : ∀ a : M, a * a = a)
include hidem

lemma isAperiodicMonoid_of_idem : IsAperiodicMonoid M :=
  ⟨fun a => ⟨1, one_pos, by rw [pow_one, pow_succ, pow_one, hidem]⟩⟩

variable {α : Type*} [DecidableEq α]

lemma prod_mul_self_of_idem (f : α → M) (s : Finset α) :
    (∏ i ∈ s, f i) * ∏ i ∈ s, f i = ∏ i ∈ s, f i := by
  rw [← Finset.prod_mul_distrib]
  exact Finset.prod_congr rfl fun i _ => hidem _

lemma prod_mul_prod_of_subset_of_idem (f : α → M) {A B : Finset α} (h : B ⊆ A) :
    (∏ i ∈ A, f i) * ∏ i ∈ B, f i = ∏ i ∈ A, f i := by
  rw [← Finset.prod_sdiff h, mul_assoc, prod_mul_self_of_idem hidem]

lemma prod_union_of_idem (f : α → M) (A B : Finset α) :
    ∏ i ∈ A ∪ B, f i = (∏ i ∈ A, f i) * ∏ i ∈ B, f i := by
  rw [← Finset.prod_union_inter,
    prod_mul_prod_of_subset_of_idem hidem f Finset.inter_subset_union]

variable {ι : Type*} [Fintype ι] [DecidableEq ι] (m : σ → M) (x : ι → σ) (T : Finset ι)

/-- **The collision argument**: a context-product collision between two
subsets of the essential set with `i` in one but not the other makes `i`
inessential. -/
lemma ctxProd_ne_of_mem_of_notMem {S S' : Finset ι} (hS : S ⊆ prodEss m x T)
    (hS' : S' ⊆ prodEss m x T) {i : ι} (hiS : i ∈ S) (hiS' : i ∉ S') :
    ctxProd m x T S ≠ ctxProd m x T S' := by
  intro heq
  have : IsAperiodicMonoid M := isAperiodicMonoid_of_idem hidem
  have : Nonempty ι := ⟨i⟩
  have hiE : i ∈ prodEss m x T := hS hiS
  obtain ⟨hiT, hne⟩ := mem_prodEss'.mp hiE
  apply hne
  have hUE : S' ∪ (prodEss m x T \ S) ⊆ (prodEss m x T).erase i := by
    intro j hj
    rcases Finset.mem_union.mp hj with hj | hj
    · exact Finset.mem_erase.mpr ⟨fun h => hiS' (h ▸ hj), hS' hj⟩
    · obtain ⟨hjE, hjS⟩ := Finset.mem_sdiff.mp hj
      exact Finset.mem_erase.mpr ⟨fun h => hjS (h ▸ hiS), hjE⟩
  -- `∏ T = c(U)` for `U = S' ∪ (E ∖ S)`
  have hTU : ∏ j ∈ T, m (x j) = ctxProd m x T (S' ∪ (prodEss m x T \ S)) := by
    rw [← ctxProd_prodEss m x T, ← ctxProd_mul_sdiff' m x T hS, heq, ctxProd, ctxProd,
      mul_assoc, ← prod_union_of_idem hidem]
  -- `c(E) = c(E ∖ {i}) · xᵢ` and `c(E ∖ {i}) = c(U) · z`
  have hEi : ctxProd m x T (prodEss m x T)
      = ctxProd m x T ((prodEss m x T).erase i) * m (x i) := by
    rw [← ctxProd_insert m x T (Finset.notMem_erase i _), Finset.insert_erase hiE]
  have hUz : ctxProd m x T (S' ∪ (prodEss m x T \ S))
      * ∏ j ∈ (prodEss m x T).erase i \ (S' ∪ (prodEss m x T \ S)), m (x j)
      = ctxProd m x T ((prodEss m x T).erase i) :=
    ctxProd_mul_sdiff' m x T hUE
  have habs : ctxProd m x T (S' ∪ (prodEss m x T \ S))
      * ((∏ j ∈ (prodEss m x T).erase i \ (S' ∪ (prodEss m x T \ S)), m (x j)) * m (x i))
      = ctxProd m x T (S' ∪ (prodEss m x T \ S)) := by
    rw [← mul_assoc, hUz, ← hEi, ctxProd_prodEss, hTU]
  have hz := mul_right_absorb habs
  -- hence `∏ T∖{i} = c(E∖{i}) = c(U) = ∏ T`
  have hTi : ∏ j ∈ T.erase i, m (x j) = ctxProd m x T ((prodEss m x T).erase i) := by
    rw [← ctxProd_erase_mul_sdiff m x T (subset_refl _) hiE, Finset.sdiff_self,
      Finset.prod_empty, mul_one]
  rw [hTi, ← hUz, hz, hTU]

/-- **Subset products of an essential set are distinct**: `2^{|E|} ≤ |M|`. -/
theorem two_pow_card_prodEss_le_of_idem :
    2 ^ (prodEss m x T).card ≤ Fintype.card M := by
  classical
  have hinj : Set.InjOn (fun S => ctxProd m x T S)
      ((prodEss m x T).powerset : Set (Finset ι)) := by
    intro S hS S' hS' heq
    simp only [Finset.coe_powerset, Set.mem_preimage, Set.mem_powerset_iff,
      Finset.coe_subset] at hS hS'
    by_contra hne
    by_cases hsub : S ⊆ S'
    · obtain ⟨i, hiS', hiS⟩ :=
        Finset.exists_of_ssubset (Finset.ssubset_iff_subset_ne.mpr ⟨hsub, hne⟩)
      exact ctxProd_ne_of_mem_of_notMem hidem m x T hS' hS hiS' hiS heq.symm
    · obtain ⟨i, hiS, hiS'⟩ := Finset.not_subset.mp hsub
      exact ctxProd_ne_of_mem_of_notMem hidem m x T hS hS' hiS hiS' heq
  calc 2 ^ (prodEss m x T).card = (prodEss m x T).powerset.card :=
        (Finset.card_powerset _).symm
    _ ≤ (Finset.univ : Finset M).card :=
        Finset.card_le_card_of_injOn _ (fun _ _ => Finset.mem_univ _) hinj
    _ = Fintype.card M := Finset.card_univ

/-- **`β ≤ ⌊log₂ |M|⌋`** for a finite commutative idempotent monoid
(`thm:semilattice-product`, breadth clause). -/
theorem breadth_le_log_of_idem : breadth m ≤ Nat.log 2 (Fintype.card M) := by
  have : IsAperiodicMonoid M := isAperiodicMonoid_of_idem hidem
  exact breadth_le_of_width m fun _ x T =>
    Nat.le_log_of_pow_le one_lt_two (two_pow_card_prodEss_le_of_idem hidem m x T)

end Idempotent

/-! ## Index two and index `k` -/

/-- `β` of the empty word's alphabet is bounded by anything nonnegative; the
`n = 0` case of the transports below. -/
lemma card_prodEss_fin_zero (m : σ → M) (x : Fin 0 → σ) (T : Finset (Fin 0)) :
    (prodEss m x T).card = 0 := by
  have h : (prodEss m x T).card ≤ Fintype.card (Fin 0) :=
    (Finset.card_le_card (prodEss_subset' m x T)).trans (Finset.card_le_univ T)
  rw [Fintype.card_fin] at h
  omega

/-- **`β < 5·log₂|M|`** under `x³ = x²` (`thm:index-two-width`, breadth
clause). -/
theorem breadth_lt_five_logb (hx3 : ∀ z : M, z ^ 3 = z ^ 2) (hM : 2 ≤ Fintype.card M)
    (m : σ → M) : (breadth m : ℝ) < 5 * Real.logb 2 (Fintype.card M) := by
  have : IsAperiodicMonoid M := isAperiodicMonoid_of_cube_eq_sq hx3
  have hlog : 0 < Real.logb 2 (Fintype.card M) :=
    Real.logb_pos one_lt_two (by exact_mod_cast hM)
  obtain ⟨n, x, hx⟩ := exists_card_prodEss_eq_breadth m
  rw [← hx]
  rcases Nat.eq_zero_or_pos n with hn | hn
  · subst hn
    rw [card_prodEss_fin_zero]
    push_cast
    positivity
  · have : Nonempty (Fin n) := ⟨⟨0, hn⟩⟩
    exact card_prodEss_lt_five_logb hx3 m x Finset.univ hM

/-- **`β ≤ 2⁶²·(k+1)·t·log₂ t`** at `t = max 2 ⌈log₂|M|⌉` under `x^{k+1} = x^k`
(`thm:index-k-width`, breadth clause; the constant is that of
`Width/IndexK.lean`). -/
theorem breadth_le_bcw {k : ℕ} (hxk : ∀ w : M, w ^ (k + 1) = w ^ k) (hk : 0 < k)
    (m : σ → M) :
    (breadth m : ℝ) ≤ 2 ^ 62 * ((k : ℝ) + 1) * bcwT M * Real.logb 2 (bcwT M) := by
  have : IsAperiodicMonoid M := ⟨fun a => ⟨k, hk, (hxk a).symm⟩⟩
  obtain ⟨n, x, hx⟩ := exists_card_prodEss_eq_breadth m
  rw [← hx]
  rcases Nat.eq_zero_or_pos n with hn | hn
  · subst hn
    rw [card_prodEss_fin_zero]
    push_cast
    have hlog : 0 ≤ Real.logb 2 (bcwT M) := zero_le_one.trans (one_le_logb_bcwT M)
    positivity
  · have : Nonempty (Fin n) := ⟨⟨0, hn⟩⟩
    exact card_prodEss_le_bcw hxk hk m x Finset.univ

end MonoidProduct
