import MonoidProduct.Dyck.Monoid.Defs
import Mathlib.Data.Fintype.Sigma
import Mathlib.Data.Fintype.Prod
import Mathlib.Data.Fintype.Option
import Mathlib.Algebra.BigOperators.Fin

set_option linter.style.header false
set_option linter.unusedSectionVars false
set_option linter.style.show false

/-!
# The normal form of the Dyck transition monoid

The normal form and cardinality of `prop:dyck-monoid`.

A nonzero element of the depth-`k` counter monoid is a **valid triple**
`(a, b, e)`: the partial translation `h ↦ h + e`, defined on `a ≤ h ≤ k - b`.
`DyckNF k` adjoins the zero (everywhere-dead) map.

The multiplication is *defined* by a max-formula (`DyckTriple.comp`),
but none of its algebra is proved by max-juggling: the semantic map `toEnd`
into `ThenEnd (DyckState k)` is proved injective (`toEnd_injective` —
the least live state recovers `a`, the greatest recovers `b`, any value
recovers `e`) and multiplicative (`toEnd_mul`, the evaluation theorem), and
associativity and unitality then transport back along the injection.  That is,
associativity is proved by injectivity of the semantic map.

The realization is `toEnd_live_eq`: every valid triple is the word
`d^a u^(a+b) d^(b-e)` in the letter actions, and zero is `d^(k+1)`, so the
explicit finite type is the transition monoid generated by the two letters.

The count: `DyckTriple k ≃ Σ s : Fin (k+1), Fin (s+1) × Fin (s+1)` (level
`s = a + b`, coordinates `a` and `e + a`), giving

  `card (DyckNF k) = (∑ s ≤ k, (s+1)²) + 1 = (k+1)(k+2)(2k+3)/6 + 1`,

with the sizes `6, 15, 31, 56, 92, 141` at `k = 1, …, 6` checked at
the bottom of the file.
-/

namespace MonoidProduct

/-! ## Valid triples -/

/-- A valid triple: the partial translation by `e` defined on
heights `a ≤ h ≤ k - b`.  Validity makes the domain nonempty and the image
stay in `[0, k]`. -/
structure DyckTriple (k : ℕ) where
  /-- The largest prefix deficit: heights below `a` die. -/
  a : ℕ
  /-- The largest prefix excess: heights above `k - b` die. -/
  b : ℕ
  /-- The total shift applied to a surviving height. -/
  e : ℤ
  /-- The domain `[a, k-b]` is nonempty. -/
  budget : a + b ≤ k
  /-- The bottom of the domain lands at `a + e ≥ 0`. -/
  lower : -(a : ℤ) ≤ e
  /-- The top of the domain lands at `(k - b) + e ≤ k`. -/
  upper : e ≤ (b : ℤ)

variable {k : ℕ}

lemma DyckTriple.ext {t t' : DyckTriple k} (ha : t.a = t'.a)
    (hb : t.b = t'.b) (he : t.e = t'.e) : t = t' := by
  obtain ⟨a, b, e, p1, p2, p3⟩ := t
  obtain ⟨a', b', e', q1, q2, q3⟩ := t'
  dsimp at ha hb he
  subst ha
  subst hb
  subst he
  rfl

instance : DecidableEq (DyckTriple k) := fun t t' =>
  decidable_of_iff (t.a = t'.a ∧ t.b = t'.b ∧ t.e = t'.e)
    ⟨fun h => DyckTriple.ext h.1 h.2.1 h.2.2,
      fun h => by rw [h]; exact ⟨rfl, rfl, rfl⟩⟩

/-! ## The semantic action of a triple -/

namespace DyckTriple

/-- The liveness condition: the height `h` is in the domain `[a, k - b]`. -/
def Lives (t : DyckTriple k) (h : Fin (k + 1)) : Prop :=
  t.a ≤ (h : ℕ) ∧ (h : ℕ) + t.b ≤ k

instance (t : DyckTriple k) (h : Fin (k + 1)) : Decidable (t.Lives h) :=
  inferInstanceAs (Decidable (_ ∧ _))

/-- The partial translation itself. -/
def apply (t : DyckTriple k) (h : Fin (k + 1)) : DyckState k :=
  if hl : t.Lives h then
    some ⟨(((h : ℕ) : ℤ) + t.e).toNat, by
      obtain ⟨h1, h2⟩ := hl
      have h3 := t.lower
      have h4 := t.upper
      omega⟩
  else none

lemma apply_def (t : DyckTriple k) (h : Fin (k + 1)) :
    t.apply h = if hl : t.Lives h then
      some ⟨(((h : ℕ) : ℤ) + t.e).toNat, by
        obtain ⟨h1, h2⟩ := hl
        have h3 := t.lower
        have h4 := t.upper
        omega⟩
    else none := rfl

lemma apply_of_lives {t : DyckTriple k} {h : Fin (k + 1)} (hl : t.Lives h) :
    ∃ h' : Fin (k + 1), t.apply h = some h'
      ∧ ((h' : ℕ) : ℤ) = ((h : ℕ) : ℤ) + t.e := by
  refine ⟨⟨(((h : ℕ) : ℤ) + t.e).toNat, ?_⟩, ?_, ?_⟩
  · obtain ⟨h1, h2⟩ := hl
    have h3 := t.lower
    have h4 := t.upper
    omega
  · rw [apply_def, dif_pos hl]
  · show ((((h : ℕ) : ℤ) + t.e).toNat : ℤ) = ((h : ℕ) : ℤ) + t.e
    have h1 := hl.1
    have h3 := t.lower
    omega

lemma apply_of_not_lives {t : DyckTriple k} {h : Fin (k + 1)}
    (hl : ¬ t.Lives h) : t.apply h = none := by
  rw [apply_def, dif_neg hl]

lemma lives_of_apply_eq_some {t : DyckTriple k} {h h' : Fin (k + 1)}
    (he : t.apply h = some h') :
    t.Lives h ∧ ((h' : ℕ) : ℤ) = ((h : ℕ) : ℤ) + t.e := by
  by_cases hl : t.Lives h
  · obtain ⟨h'', hs, hv⟩ := apply_of_lives hl
    rw [hs] at he
    obtain rfl := Option.some.inj he
    exact ⟨hl, hv⟩
  · rw [apply_of_not_lives hl] at he
    simp at he

/-- The least live height. -/
def bot (t : DyckTriple k) : Fin (k + 1) := ⟨t.a, by have := t.budget; omega⟩

/-- The greatest live height. -/
def top (t : DyckTriple k) : Fin (k + 1) := ⟨k - t.b, by omega⟩

@[simp] lemma bot_val (t : DyckTriple k) : ((t.bot : Fin (k + 1)) : ℕ) = t.a :=
  rfl

@[simp] lemma top_val (t : DyckTriple k) :
    ((t.top : Fin (k + 1)) : ℕ) = k - t.b := rfl

lemma lives_bot (t : DyckTriple k) : t.Lives t.bot :=
  ⟨le_refl _, by show t.a + t.b ≤ k; exact t.budget⟩

lemma lives_top (t : DyckTriple k) : t.Lives t.top := by
  have hb := t.budget
  exact ⟨by show t.a ≤ k - t.b; omega, by show k - t.b + t.b ≤ k; omega⟩

/-- **Injectivity**: distinct valid triples induce distinct partial maps. -/
lemma eq_of_apply_eq {t t' : DyckTriple k}
    (hap : ∀ h₀, t.apply h₀ = t'.apply h₀) : t = t' := by
  have hb := t.budget
  have hb' := t'.budget
  have hlives : ∀ h, t.Lives h → t'.Lives h := fun h hl => by
    obtain ⟨x, hx, -⟩ := apply_of_lives hl
    exact (lives_of_apply_eq_some ((hap h).symm.trans hx)).1
  have hlives' : ∀ h, t'.Lives h → t.Lives h := fun h hl => by
    obtain ⟨x, hx, -⟩ := apply_of_lives hl
    exact (lives_of_apply_eq_some ((hap h).trans hx)).1
  have ha : t.a = t'.a := by
    have h1 := (hlives t.bot t.lives_bot).1
    have h2 := (hlives' t'.bot t'.lives_bot).1
    have e1 := t.bot_val
    have e2 := t'.bot_val
    omega
  have hbb : t.b = t'.b := by
    have h1 := (hlives t.top t.lives_top).2
    have h2 := (hlives' t'.top t'.lives_top).2
    have e1 := t.top_val
    have e2 := t'.top_val
    omega
  have he : t.e = t'.e := by
    obtain ⟨x, hx, hvx⟩ := apply_of_lives t.lives_bot
    obtain ⟨-, hvx'⟩ := lives_of_apply_eq_some ((hap t.bot).symm.trans hx)
    omega
  exact DyckTriple.ext ha hbb he

end DyckTriple

/-! ## The normal form -/

/-- The transition monoid in normal form: the zero map, or a valid triple. -/
inductive DyckNF (k : ℕ) where
  /-- The everywhere-dead transformation. -/
  | zero : DyckNF k
  /-- A live partial translation. -/
  | live (t : DyckTriple k) : DyckNF k
  deriving DecidableEq

namespace DyckNF

/-- The semantic map into sequential endomorphisms of the counter. -/
def toEnd : DyckNF k → ThenEnd (DyckState k)
  | .zero => ⟨fun _ => none⟩
  | .live t => ⟨fun s => s.bind t.apply⟩

@[simp] lemma toEnd_zero_run (s : DyckState k) :
    (DyckNF.zero : DyckNF k).toEnd.run s = none := rfl

@[simp] lemma toEnd_live_run_none (t : DyckTriple k) :
    (DyckNF.live t).toEnd.run none = none := rfl

@[simp] lemma toEnd_live_run_some (t : DyckTriple k) (h : Fin (k + 1)) :
    (DyckNF.live t).toEnd.run (some h) = t.apply h := rfl

@[simp] lemma toEnd_run_none (x : DyckNF k) : x.toEnd.run none = none := by
  cases x <;> rfl

/-- **Injectivity** at the monoid level: the semantic map is injective. -/
theorem toEnd_injective : Function.Injective (DyckNF.toEnd (k := k)) := by
  intro x y hxy
  have hrun : ∀ s, x.toEnd.run s = y.toEnd.run s := fun s => by rw [hxy]
  cases x with
  | zero =>
      cases y with
      | zero => rfl
      | live t =>
          exfalso
          obtain ⟨x', hx', -⟩ := DyckTriple.apply_of_lives t.lives_bot
          have h := hrun (some t.bot)
          rw [toEnd_zero_run, toEnd_live_run_some, hx'] at h
          simp at h
  | live t =>
      cases y with
      | zero =>
          exfalso
          obtain ⟨x', hx', -⟩ := DyckTriple.apply_of_lives t.lives_bot
          have h := hrun (some t.bot)
          rw [toEnd_zero_run, toEnd_live_run_some, hx'] at h
          simp at h
      | live t' =>
          have hap : ∀ h₀, t.apply h₀ = t'.apply h₀ := fun h₀ => by
            have h := hrun (some h₀)
            rwa [toEnd_live_run_some, toEnd_live_run_some] at h
          rw [DyckTriple.eq_of_apply_eq hap]

end DyckNF

/-! ## Multiplication -/

namespace DyckTriple

/-- The composed triple, when the composite domain is nonempty: the
max-formula `a' = max a₁ (a₂ - e₁)`, `b' = max b₁ (b₂ + e₁)`, `e' = e₁ + e₂`, computed in
`ℤ` and converted back after nonnegativity (both maxima dominate a natural). -/
def compT (t₁ t₂ : DyckTriple k)
    (hk : max (t₁.a : ℤ) ((t₂.a : ℤ) - t₁.e)
      + max (t₁.b : ℤ) ((t₂.b : ℤ) + t₁.e) ≤ (k : ℤ)) : DyckTriple k where
  a := (max (t₁.a : ℤ) ((t₂.a : ℤ) - t₁.e)).toNat
  b := (max (t₁.b : ℤ) ((t₂.b : ℤ) + t₁.e)).toNat
  e := t₁.e + t₂.e
  budget := by omega
  lower := by have := t₂.lower; omega
  upper := by have := t₂.upper; omega

@[simp] lemma compT_a (t₁ t₂ : DyckTriple k) (hk) :
    (t₁.compT t₂ hk).a = (max (t₁.a : ℤ) ((t₂.a : ℤ) - t₁.e)).toNat := rfl

@[simp] lemma compT_b (t₁ t₂ : DyckTriple k) (hk) :
    (t₁.compT t₂ hk).b = (max (t₁.b : ℤ) ((t₂.b : ℤ) + t₁.e)).toNat := rfl

@[simp] lemma compT_e (t₁ t₂ : DyckTriple k) (hk) :
    (t₁.compT t₂ hk).e = t₁.e + t₂.e := rfl

/-- Sequential composition of two triples: the composed triple if its domain
is nonempty, zero otherwise. -/
def comp (t₁ t₂ : DyckTriple k) : DyckNF k :=
  if hk : max (t₁.a : ℤ) ((t₂.a : ℤ) - t₁.e)
      + max (t₁.b : ℤ) ((t₂.b : ℤ) + t₁.e) ≤ (k : ℤ) then
    .live (t₁.compT t₂ hk)
  else .zero

/-- **The evaluation theorem for `comp`**: composing the partial maps.  This
is the only place the max-formula is compared with semantics; every algebraic
law is derived from it by injectivity. -/
lemma comp_run (t₁ t₂ : DyckTriple k) (h : Fin (k + 1)) :
    (t₁.comp t₂).toEnd.run (some h) = (t₁.apply h).bind t₂.apply := by
  have hb1 := t₁.budget
  have hlo1 := t₁.lower
  have hup1 := t₁.upper
  have hb2 := t₂.budget
  have hlo2 := t₂.lower
  have hup2 := t₂.upper
  have hh := h.isLt
  unfold comp
  split_ifs with hk
  · rw [DyckNF.toEnd_live_run_some]
    have hTa := compT_a t₁ t₂ hk
    have hTb := compT_b t₁ t₂ hk
    have hTe := compT_e t₁ t₂ hk
    by_cases hL : (t₁.compT t₂ hk).Lives h
    · have hc1 := hL.1
      have hc2 := hL.2
      have hL1 : t₁.Lives h := ⟨by omega, by omega⟩
      obtain ⟨x₁, hx₁, hv₁⟩ := apply_of_lives hL1
      have hL2 : t₂.Lives x₁ := ⟨by omega, by omega⟩
      obtain ⟨x₂, hx₂, hv₂⟩ := apply_of_lives hL2
      obtain ⟨x₀, hx₀, hv₀⟩ := apply_of_lives hL
      rw [hx₀, hx₁]
      show some x₀ = t₂.apply x₁
      rw [hx₂]
      exact congrArg some (Fin.ext (by omega))
    · rw [apply_of_not_lives hL]
      symm
      cases hx₁ : t₁.apply h with
      | none => rfl
      | some x₁ =>
          obtain ⟨hL1, hv₁⟩ := lives_of_apply_eq_some hx₁
          show t₂.apply x₁ = none
          cases hx₂ : t₂.apply x₁ with
          | none => rfl
          | some x₂ =>
              exfalso
              obtain ⟨hL2, -⟩ := lives_of_apply_eq_some hx₂
              obtain ⟨h1, h2⟩ := hL1
              obtain ⟨h3, h4⟩ := hL2
              exact hL ⟨by omega, by omega⟩
  · rw [DyckNF.toEnd_zero_run]
    symm
    cases hx₁ : t₁.apply h with
    | none => rfl
    | some x₁ =>
        obtain ⟨hL1, hv₁⟩ := lives_of_apply_eq_some hx₁
        show t₂.apply x₁ = none
        cases hx₂ : t₂.apply x₁ with
        | none => rfl
        | some x₂ =>
            exfalso
            obtain ⟨hL2, -⟩ := lives_of_apply_eq_some hx₂
            obtain ⟨h1, h2⟩ := hL1
            obtain ⟨h3, h4⟩ := hL2
            exact hk (by omega)

end DyckTriple

namespace DyckNF

instance : Mul (DyckNF k) :=
  ⟨fun x y => match x, y with
    | .zero, _ => .zero
    | _, .zero => .zero
    | .live t₁, .live t₂ => t₁.comp t₂⟩

@[simp] lemma zero_mul_eq (y : DyckNF k) :
    (DyckNF.zero : DyckNF k) * y = DyckNF.zero := rfl

@[simp] lemma mul_zero_eq (x : DyckNF k) :
    x * (DyckNF.zero : DyckNF k) = DyckNF.zero := by cases x <;> rfl

@[simp] lemma live_mul_live (t₁ t₂ : DyckTriple k) :
    (DyckNF.live t₁ : DyckNF k) * DyckNF.live t₂ = t₁.comp t₂ := rfl

/-- **The evaluation theorem**: the semantic map is
multiplicative for the sequential composition. -/
theorem toEnd_mul (x y : DyckNF k) : (x * y).toEnd = x.toEnd * y.toEnd := by
  refine ThenEnd.ext fun s => ?_
  rw [ThenEnd.mul_run]
  cases x with
  | zero =>
      rw [zero_mul_eq, toEnd_zero_run, toEnd_run_none]
  | live t₁ =>
      cases y with
      | zero =>
          rw [mul_zero_eq, toEnd_zero_run, toEnd_zero_run]
      | live t₂ =>
          rw [live_mul_live]
          cases s with
          | none => rw [toEnd_run_none, toEnd_live_run_none, toEnd_run_none]
          | some h => rw [DyckTriple.comp_run, toEnd_live_run_some]; rfl

/-- The identity triple `(0, 0, 0)`: total, shift by nothing. -/
def oneT (k : ℕ) : DyckTriple k :=
  ⟨0, 0, 0, Nat.zero_le k, by norm_num, by norm_num⟩

instance : One (DyckNF k) := ⟨.live (oneT k)⟩

lemma one_def : (1 : DyckNF k) = .live (oneT k) := rfl

theorem toEnd_one : (1 : DyckNF k).toEnd = 1 := by
  refine ThenEnd.ext fun s => ?_
  rw [ThenEnd.one_run]
  cases s with
  | none => rw [one_def, toEnd_live_run_none]
  | some h =>
      rw [one_def, toEnd_live_run_some]
      have hL : (oneT k).Lives h :=
        ⟨Nat.zero_le _, by show (h : ℕ) + 0 ≤ k; have := h.isLt; omega⟩
      obtain ⟨h', hs, hv⟩ := DyckTriple.apply_of_lives hL
      rw [hs]
      have he : (oneT k).e = 0 := rfl
      exact congrArg some (Fin.ext (by omega))

/-- The monoid structure: associativity and unitality are transported from
`ThenEnd` along the injective multiplicative map — no max-calculation. -/
instance : Monoid (DyckNF k) where
  mul_assoc x y z := toEnd_injective (by
    rw [toEnd_mul, toEnd_mul, toEnd_mul, toEnd_mul, mul_assoc])
  one_mul x := toEnd_injective (by rw [toEnd_mul, toEnd_one, one_mul])
  mul_one x := toEnd_injective (by rw [toEnd_mul, toEnd_one, mul_one])

/-- The semantic map as a monoid homomorphism. -/
def toEndHom (k : ℕ) : DyckNF k →* ThenEnd (DyckState k) where
  toFun := DyckNF.toEnd
  map_one' := toEnd_one
  map_mul' := toEnd_mul

/-! ## Realization by words -/

/-- **Realization**: every valid triple is realized by the word `d^a u^(a+b)
d^(b-e)`. -/
theorem toEnd_live_eq (t : DyckTriple k) :
    (DyckNF.live t).toEnd
      = downE k ^ t.a * upE k ^ (t.a + t.b)
        * downE k ^ ((t.b : ℤ) - t.e).toNat := by
  have hb := t.budget
  have hlo := t.lower
  have hup := t.upper
  refine ThenEnd.ext fun s => ?_
  rw [ThenEnd.mul_run, ThenEnd.mul_run]
  cases s with
  | none =>
      rw [toEnd_live_run_none, ThenEnd.pow_run_fixed (downE_run_none k),
        ThenEnd.pow_run_fixed (upE_run_none k),
        ThenEnd.pow_run_fixed (downE_run_none k)]
  | some h =>
      rw [toEnd_live_run_some]
      by_cases h1 : t.a ≤ (h : ℕ)
      · rw [downE_pow_run_of_le h1]
        by_cases h2 : (h : ℕ) + t.b ≤ k
        · rw [upE_pow_run_of_le
            (by show (h : ℕ) - t.a + (t.a + t.b) ≤ k; omega)]
          rw [downE_pow_run_of_le (by
            show ((t.b : ℤ) - t.e).toNat ≤ (h : ℕ) - t.a + (t.a + t.b)
            omega)]
          obtain ⟨h', hs, hv⟩ :=
            DyckTriple.apply_of_lives (t := t) (h := h) ⟨h1, h2⟩
          rw [hs]
          exact congrArg some (Fin.ext (by
            show (h' : ℕ)
              = (h : ℕ) - t.a + (t.a + t.b) - ((t.b : ℤ) - t.e).toNat
            omega))
        · rw [upE_pow_run_of_gt
            (by show k < (h : ℕ) - t.a + (t.a + t.b); omega),
            ThenEnd.pow_run_fixed (downE_run_none k),
            DyckTriple.apply_of_not_lives (fun hL => h2 hL.2)]
      · rw [downE_pow_run_of_gt (by omega),
          ThenEnd.pow_run_fixed (upE_run_none k),
          ThenEnd.pow_run_fixed (downE_run_none k),
          DyckTriple.apply_of_not_lives (fun hL => h1 hL.1)]

/-- **Realization**: the zero map is realized by `d^(k+1)`. -/
theorem toEnd_zero_eq :
    (DyckNF.zero : DyckNF k).toEnd = downE k ^ (k + 1) := by
  refine ThenEnd.ext fun s => ?_
  cases s with
  | none =>
      rw [toEnd_zero_run, ThenEnd.pow_run_fixed (downE_run_none k)]
  | some h =>
      rw [toEnd_zero_run, downE_pow_run_of_gt h.isLt]

end DyckNF

/-! ## Cardinality (`prop:dyck-monoid`) -/

/-- Componentwise equality suffices in the counting sigma type; this is the
`HEq`-free route, splitting on the first component first. -/
lemma sigma_fin_ext
    {x y : Σ s : Fin (k + 1), Fin ((s : ℕ) + 1) × Fin ((s : ℕ) + 1)}
    (h1 : ((x.1 : Fin (k + 1)) : ℕ) = ((y.1 : Fin (k + 1)) : ℕ))
    (h2 : ((x.2.1) : ℕ) = ((y.2.1) : ℕ))
    (h3 : ((x.2.2) : ℕ) = ((y.2.2) : ℕ)) : x = y := by
  obtain ⟨s, i, j⟩ := x
  obtain ⟨s', i', j'⟩ := y
  obtain rfl : s = s' := Fin.ext h1
  refine congrArg (Sigma.mk s) ?_
  exact Prod.ext (Fin.ext h2) (Fin.ext h3)

/-- **Cardinality**: a valid triple is a level `s = a + b ≤ k` together with the two
coordinates `a ∈ [0, s]` and `e + a ∈ [0, s]`. -/
def dyckTripleEquiv (k : ℕ) :
    DyckTriple k ≃ Σ s : Fin (k + 1), Fin ((s : ℕ) + 1) × Fin ((s : ℕ) + 1) where
  toFun t :=
    ⟨⟨t.a + t.b, by have := t.budget; omega⟩,
      ⟨t.a, by show t.a < t.a + t.b + 1; omega⟩,
      ⟨(t.e + (t.a : ℤ)).toNat, by
        show (t.e + (t.a : ℤ)).toNat < t.a + t.b + 1
        have := t.lower
        have := t.upper
        omega⟩⟩
  invFun x :=
    ⟨(x.2.1 : ℕ), (x.1 : ℕ) - (x.2.1 : ℕ),
      ((x.2.2 : ℕ) : ℤ) - ((x.2.1 : ℕ) : ℤ),
      by have := x.1.isLt; have := x.2.1.isLt; omega,
      by omega,
      by have := x.2.1.isLt; have := x.2.2.isLt; omega⟩
  left_inv t := by
    have hlo := t.lower
    refine DyckTriple.ext rfl ?_ ?_
    · show t.a + t.b - t.a = t.b
      omega
    · show ((t.e + (t.a : ℤ)).toNat : ℤ) - ((t.a : ℕ) : ℤ) = t.e
      omega
  right_inv := by
    rintro ⟨s, i, j⟩
    have his := i.isLt
    have hjs := j.isLt
    apply sigma_fin_ext
    · show (i : ℕ) + ((s : ℕ) - (i : ℕ)) = (s : ℕ)
      omega
    · rfl
    · show ((((j : ℕ) : ℤ) - ((i : ℕ) : ℤ)) + ((i : ℕ) : ℤ)).toNat = (j : ℕ)
      omega

instance : Fintype (DyckTriple k) :=
  Fintype.ofEquiv _ (dyckTripleEquiv k).symm

/-- `DyckNF` is `Option` of the triples. -/
def dyckNFEquivOption (k : ℕ) : DyckNF k ≃ Option (DyckTriple k) where
  toFun x := match x with
    | .zero => none
    | .live t => some t
  invFun x := match x with
    | none => .zero
    | some t => .live t
  left_inv x := by cases x <;> rfl
  right_inv x := by cases x <;> rfl

instance : Fintype (DyckNF k) :=
  Fintype.ofEquiv _ (dyckNFEquivOption k).symm

theorem card_dyckTriple (k : ℕ) :
    Fintype.card (DyckTriple k) = ∑ s ∈ Finset.range (k + 1), (s + 1) ^ 2 := by
  rw [Fintype.card_congr (dyckTripleEquiv k), Fintype.card_sigma]
  simp only [Fintype.card_prod, Fintype.card_fin]
  rw [Fin.sum_univ_eq_sum_range (fun s => (s + 1) * (s + 1)) (k + 1)]
  exact Finset.sum_congr rfl fun s _ => (pow_two _).symm

/-- **Cardinality**, sum form. -/
theorem card_dyckNF_sum (k : ℕ) :
    Fintype.card (DyckNF k)
      = (∑ s ∈ Finset.range (k + 1), (s + 1) ^ 2) + 1 := by
  rw [Fintype.card_congr (dyckNFEquivOption k), Fintype.card_option,
    card_dyckTriple]

/-- **Cardinality**, closed form: `(k+1)(k+2)(2k+3)/6 + 1`, the division exact. -/
theorem card_dyckNF_closed (k : ℕ) :
    Fintype.card (DyckNF k) = (k + 1) * (k + 2) * (2 * k + 3) / 6 + 1 := by
  have h6 : 6 * ∑ s ∈ Finset.range (k + 1), (s + 1) ^ 2
      = (k + 1) * (k + 2) * (2 * k + 3) := by
    induction k with
    | zero => rw [Finset.sum_range_one]; norm_num
    | succ k ih => rw [Finset.sum_range_succ, mul_add, ih]; ring
  rw [card_dyckNF_sum, ← h6,
    Nat.mul_div_cancel_left _ (by norm_num : (0 : ℕ) < 6)]

/-! ## The sizes for small `k` -/

example : Fintype.card (DyckNF 1) = 6 := by
  rw [card_dyckNF_sum]; norm_num [Finset.sum_range_succ]
example : Fintype.card (DyckNF 2) = 15 := by
  rw [card_dyckNF_sum]; norm_num [Finset.sum_range_succ]
example : Fintype.card (DyckNF 3) = 31 := by
  rw [card_dyckNF_sum]; norm_num [Finset.sum_range_succ]
example : Fintype.card (DyckNF 4) = 56 := by
  rw [card_dyckNF_sum]; norm_num [Finset.sum_range_succ]
example : Fintype.card (DyckNF 5) = 92 := by
  rw [card_dyckNF_sum]; norm_num [Finset.sum_range_succ]
example : Fintype.card (DyckNF 6) = 141 := by
  rw [card_dyckNF_sum]; norm_num [Finset.sum_range_succ]

end MonoidProduct
